name = "asas-crm"
main = "src/index.ts"
compatibility_date = "2026-05-16"
compatibility_flags = ["nodejs_compat"]

[vars]
# These will be overridden by wrangler secret put
DATABASE_URL = "postgresql://neondb_owner:npg_YRLDTh3z0gFx@ep-silent-violet-aqdwsns0.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require"
JWT_SECRET = "2gxbZAixbC67Lx8NJMdMejSMepbWkUaVD3OtUUtvE13"
#R2_PUBLIC_URL = "https://your-bucket.r2.dev"

# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "asas-crm-documents"
