name = "asas-crm"
main = "src/index.ts"
compatibility_date = "2026-05-16"
compatibility_flags = ["nodejs_compat"]
environment = "production"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "asas-crm-documents"
